import 'package:flutter_bluetooth_serial_example/cars_data/cars_features_lists.dart';
import 'package:flutter_bluetooth_serial_example/models/car.dart';

List<Car> cars = [
  Car(
      id: 0,
      name: 'MEGANE',
      fullName: 'RENAULT MEGANE',
      imageWithoutBackground: 'assets/images/car_image.png',
      year: 2023,
      cc: 1600,
      hp: 115,
      seatsNo: 5,
      topSpeed: 240,
      description:
          'تمتع بالمواد الراقية وخامات السيارة عالية الجودة, جميع المكونات الداخلية في سيارة رينو ميجان الجديدة مطعمة بالكروم والمزيد. تهتم ميجان بالتفاصيل..',
      engineFeatures: FirstCarFeatures.engineFeatures,
      performanceFeatures: FirstCarFeatures.performanceFeatures,
      interiorFeatures: FirstCarFeatures.interiorFeatures,
      exteriorFeatures: FirstCarFeatures.exteriorFeatures,
      techFeatures: FirstCarFeatures.techFeatures),
  Car(
      id: 1,
      name: 'MEGANE',
      fullName: 'RENAULT MEGANE',
      imageWithoutBackground: 'assets/images/car_image.png',
      year: 2023,
      cc: 1600,
      hp: 115,
      seatsNo: 5,
      topSpeed: 240,
      description:
          'تمتع بالمواد الراقية وخامات السيارة عالية الجودة, جميع المكونات الداخلية في سيارة رينو ميجان الجديدة مطعمة بالكروم والمزيد. تهتم ميجان بالتفاصيل..',
      engineFeatures: SecondCarFeatures.engineFeatures,
      performanceFeatures: SecondCarFeatures.performanceFeatures,
      interiorFeatures: SecondCarFeatures.interiorFeatures,
      exteriorFeatures: SecondCarFeatures.exteriorFeatures,
      techFeatures: SecondCarFeatures.techFeatures),
  Car(
      id: 2,
      name: 'MEGANE',
      fullName: 'RENAULT MEGANE',
      imageWithoutBackground: 'assets/images/car_image.png',
      year: 2023,
      cc: 1600,
      hp: 120,
      seatsNo: 5,
      topSpeed: 240,
      description:
          'تمتع بالمواد الراقية وخامات السيارة عالية الجودة, جميع المكونات الداخلية في سيارة رينو ميجان الجديدة مطعمة بالكروم والمزيد. تهتم ميجان بالتفاصيل..',
      engineFeatures: ThirdCarFeatures.engineFeatures,
      performanceFeatures: ThirdCarFeatures.performanceFeatures,
      interiorFeatures: ThirdCarFeatures.interiorFeatures,
      exteriorFeatures: ThirdCarFeatures.exteriorFeatures,
      techFeatures: ThirdCarFeatures.techFeatures),
  Car(
      id: 3,
      name: 'MEGANE',
      fullName: 'RENAULT MEGANE',
      imageWithoutBackground: 'assets/images/car_image.png',
      year: 2023,
      cc: 1600,
      hp: 115,
      seatsNo: 5,
      topSpeed: 240,
      description:
          'تمتع بالمواد الراقية وخامات السيارة عالية الجودة, جميع المكونات الداخلية في سيارة رينو ميجان الجديدة مطعمة بالكروم والمزيد. تهتم ميجان بالتفاصيل..',
      engineFeatures: ForthCarFeatures.engineFeatures,
      performanceFeatures: ForthCarFeatures.performanceFeatures,
      interiorFeatures: ForthCarFeatures.interiorFeatures,
      exteriorFeatures: ForthCarFeatures.exteriorFeatures,
      techFeatures: ForthCarFeatures.techFeatures),
];
